apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:  
            matchLabels:
              app: app
      containers:
        - name: app
          image: 649257189115.dkr.ecr.us-east-1.amazonaws.com/app:latest
          env:
            - name: SPRING_PROFILES_ACTIVE 
              value: "dev-new"
            - name: CORALOGIX_LOG_URL
              value: "https://api.coralogix.us/api/v1/logs"
            - name: newrelic.environment
              value: "dev"
          resources:
            requests:
              memory: "718Mi"
              cpu: "500m"
            limits:
              memory: "718Mi"
              cpu: "700m"
          readinessProbe:
            tcpSocket:
              port: 8080
            # httpGet:
            #  path: /actuator/health
            #  port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          ports:
            - name: http
              containerPort: 8080
            - name: rsocket
              containerPort: 6565
