apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "359"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"app","namespace":"default"},"spec":{"selector":{"matchLabels":{"app":"app"}},"template":{"metadata":{"labels":{"app":"app"}},"spec":{"containers":[{"env":[{"name":"SPRING_PROFILES_ACTIVE","value":"dev"},{"name":"CORALOGIX_LOG_URL","value":"https://api.coralogix.us/api/v1/logs"},{"name":"newrelic.environment","value":"development"}],"image":"480997871449.dkr.ecr.us-east-1.amazonaws.com/app:latest","name":"app","ports":[{"containerPort":8080,"name":"http"},{"containerPort":6565,"name":"rsocket"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/actuator/health","port":8080},"initialDelaySeconds":30,"periodSeconds":10,"timeoutSeconds":5},"resources":{"requests":{"cpu":"500m","memory":"718Mi"}}}],"topologySpreadConstraints":[{"labelSelector":{"matchLabels":{"app":"app"}},"maxSkew":1,"topologyKey":"kubernetes.io/hostname","whenUnsatisfiable":"ScheduleAnyway"}]}}}}
    creationTimestamp: "2023-08-08T06:42:00Z"
    generation: 361
    labels:
      k8slens-edit-resource-version: v1
    name: app
    namespace: default
    resourceVersion: "100993501"
    uid: a74a3d6d-4d2d-43bf-8698-c3cb1f5e179b
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: app
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: app
      spec:
        containers:
        - env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
          - name: CORALOGIX_LOG_URL
            value: https://api.coralogix.us/api/v1/logs
          - name: newrelic.environment
            value: development
          image: 480997871449.dkr.ecr.us-east-1.amazonaws.com/app:3a482127194196ef055da7a2886486d54f06d6cb
          imagePullPolicy: Always
          name: app
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 6565
            name: rsocket
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 500m
              memory: 718Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: app
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2024-07-01T11:28:43Z"
      lastUpdateTime: "2024-07-01T11:28:43Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2024-04-29T14:38:37Z"
      lastUpdateTime: "2024-07-07T15:05:35Z"
      message: ReplicaSet "app-6d5dcbbbd7" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 361
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
    
kind: List
metadata:
  resourceVersion: ""
